FROM node:22-alpine

WORKDIR /app

# เอาไฟล์ที่ขึ้นต้นด้วย package-----.json
COPY package*.json ./

RUN npm install

# (.)Host (.)container
COPY . .

EXPOSE 5173

# terminal npm run dev # เว้นระยะห่างด้วย array
CMD [ "npm", "run", "dev" ]