FROM node:22-alpine

WORKDIR /app

# เอาไฟล์ที่ขึ้นต้นด้วย package-----.json
COPY package.json ./

RUN npm install
RUN npm install -g nodemon

# (.)Host (.)container
COPY . .

EXPOSE 5000

CMD [ "nodemon", "index.js" ]